lwr:

  # Publish all joint states -----------------------------------
  kuka_joint_state_controller:
    type: lwr_controllers/KUKAJointStateController
    publish_rate: 100  
    root_name: lwr_base_link
#    tip_name: lwr_7_link
    tip_name: lwr_3_link

  joint_controllers:
    type: lwr_controllers/JointControllers
    root_name: lwr_base_link
#    tip_name: lwr_7_link
    tip_name: lwr_3_link
    max_ee_dt : 1
    max_ee_f : 5
    max_qdot : 3

  joint_controller:
    type: lwr_controllers/JointController
    root_name: lwr_base_link
#    tip_name: lwr_7_link
    tip_name: lwr_3_link
    max_ee_dt : 1
    max_ee_f : 5
    max_qdot : 3

  cartesian_controller:
    type: lwr_controllers/CartesianController
    root_name: lwr_base_link
#    tip_name: lwr_7_link
    tip_name: lwr_3_link
    max_ee_dt : 1
    max_ee_f : 5
    max_qdot : 3



